### ISSUE TITLE
Add list of URL's.

### ISSUE THREAD

**Issue by aldo-moreno-leon** [Leonmugen/ORtester#3]
Make a list of URL's to scan various websites.
With this on mind, It will be good add verbose parameter and once done, display all the vulnerable sites.

**Comment by hax0rgb** [comment]
Hi @Leonmugen 

Do you have any plans to add a feature to provide list of URL's as input. I can see the tool only supports only single url to be tested at a time. Providing the list of URL's to scan will be really useful.

**Comment by hax0rgb** [comment]
Hi @Leonmugen 

Do you have any plans to add a feature to provide list of URL's as input. I can see the tool only supports only single url to be tested at a time. Providing the list of URL's to scan will be really useful.
